#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /modules
  static_dir: modules

- url: /questions
  static_dir: questions

- url: /dare.txt
  static_dir: dare.txt

- url: /.*
  script: mainapp.app


libraries:
- name: jinja2
  version: latest
  
- name: webapp2
  version: latest
