#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /.*
  script: mainapp.app


libraries:
- name: jinja2
  version: latest
  
- name: webapp2
  version: latest
